#!/usr/bin/env dart

import 'dart:convert';
import 'dart:io';

var build64Bit = false;

Future<int> getGitCommitCount() async {
  final result = await Process.run('git', ['log', '--oneline']);
  return (result.stdout as String)
      .split('\n')
      .where((line) => line.isNotEmpty)
      .length;
}

Future<void> generateCountlyConfig() async {
  final configs = await File('countly_config').readAsLines();
  if (configs.length < 2) {
    throw Exception('''No Countly config file. 
          Please add URL and KEY by lines to 
          file countly_config in project root dir.''');
  }

  final data = {
    'url': configs[0],
    'key': configs[1],
  };

  await writeStaicConfigFile(data, 'CountlyConfig', 'lib/config/countly.dart');
}

Future<void> writeStaicConfigFile(Map<String, dynamic> data, 
                                  String className,
                                  String path) async {
  final buffer = StringBuffer();
  buffer.writeln('// This file is generated by ./make.dart');
  buffer.writeln('');
  buffer.writeln('class $className {');
  for (var entry in data.entries) {
    final type = entry.value.runtimeType;
    final value = json.encode(entry.value);
    buffer.writeln('  static const $type ${entry.key} = $value;');
  }
  buffer.writeln('}');
  await File(path).writeAsString(buffer.toString());
}

Future<int> getGitModificationCount() async {
  final result =
      await Process.run('git', ['ls-files', '-mo', '--exclude-standard']);
  return (result.stdout as String)
      .split('\n')
      .where((line) => line.isNotEmpty)
      .length;
}

Future<String> getFlutterVersion() async {
  final result = await Process.run('flutter', ['--version'], runInShell: true);
  return (result.stdout as String);
}

Future<Map<String, dynamic>> getBuildData() async {
  final data = {
    'name': 'CustedNG',
    'build': await getGitCommitCount(),
    'engine': await getFlutterVersion(),
    'buildAt': DateTime.now().toString(),
    'modifications': await getGitModificationCount(),
  };
  return data;
}

String jsonEncodeWithIndent(Map<String, dynamic> json) {
  final encoder = JsonEncoder.withIndent('  ');
  return encoder.convert(json);
}

Future<void> updateBuildData() async {
  print('Updating BuildData...');
  final data = await getBuildData();
  print(jsonEncodeWithIndent(data));
  final path = 'lib/res/build_data.dart';
  await writeStaicConfigFile(data, 'BuildData', path);
}

void flutterRun() {
  Process.start('flutter', ['run'],
      mode: ProcessStartMode.inheritStdio, runInShell: true);
}

void flutterBuildAndroid() async {
  final build = await getGitCommitCount();
  await generateCountlyConfig();

  final args = [
    'build',
    'apk',
    build64Bit
        ? '--target-platform=android-arm64'
        : '--target-platform=android-arm',
    '--build-number=$build',
    '--build-name=1.0.$build',
    '-v'
  ];
  print('Building with args: ${args.join(' ')}');
  final buildResult = await Process.run('flutter', args, runInShell: true);
  final exitCode = buildResult.exitCode;

  if (exitCode == 0) {
    final copySource = './build/app/outputs/apk/release/app-release.apk';
    final copyTarget = './CustedNG_${build}_Arm${build64Bit ? 64 : ""}.apk';
    print('Copying from $copySource to $copyTarget');

    await File(copySource).copy(copyTarget);
    print('Done.');
  } else {
    print(buildResult.stderr.toString());
    print('\nBuild failed with exit code $exitCode');
  }
}

void main(List<String> args) async {
  await updateBuildData();

  if (args.isEmpty) {
    print('No action. Exit.');
    return;
  }

  final command = args[0];

  switch (command) {
    case 'run':
      return flutterRun();
    case 'build':
      if (args.length > 1) {
        if (args[1] == 'arm64') {
          print("Building android-arm64 variant");
          build64Bit = true;
        } else {
          print("Unrecognized variant " + args[1]);
        }
      }
      return flutterBuildAndroid();
    default:
      print('Unsupported command: $command');
      return;
  }
}
