// This file is generated by ./make.dart

class BuildData {
  static const String name = "CustedNG";
  static const int build = 742;
  static const String engine =
      "Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git\nFramework • revision b8f7f1f986 (5 days ago) • 2022-11-23 06:43:51 +0900\nEngine • revision 8f2221fbef\nTools • Dart 2.18.5 • DevTools 2.15.0\n";
  static const String buildAt = "2022-11-28 13:09:49.077320";
  static const int modifications = 7;
}
