// This file is generated by ./make.dart

class BuildData {
  static const String name = "CustedNG";
  static const int build = 697;
  static const String engine =
      "Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git\nFramework • revision fb57da5f94 (7 weeks ago) • 2022-05-19 15:50:29 -0700\nEngine • revision caaafc5604\nTools • Dart 2.17.1 • DevTools 2.12.2\n";
  static const String buildAt = "2022-07-04 20:08:10.547377";
  static const int modifications = 3;
}
