///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class JwEmptyRoomDataPagingResultRowsTeachBuilding {
/*
{
  "BDJXLXXID": null,
  "JXLBH": "0001",
  "JXLMC": "东区第一教学楼东配楼",
  "YWMC": null,
  "PYSZM": null,
  "BDXQXXID": null,
  "ZYBZ": false,
  "JZWZK": null,
  "JZWLX": null,
  "DZ": null,
  "CS": null,
  "JJ": null,
  "BZ": null,
  "JYBJ": false,
  "JC": null,
  "SchoolInfo": null,
  "RoomInfos": null,
  "ID": "d91cc53c-a9ad-4be3-becf-7f3ed62e8762",
  "ZZCLBlob": null,
  "_LogCreate": null,
  "_LogUpdate": null,
  "_LogAudit": null
} 
*/

  String BDJXLXXID;
  String JXLBH;
  String JXLMC;
  String YWMC;
  String PYSZM;
  String BDXQXXID;
  bool ZYBZ;
  String JZWZK;
  String JZWLX;
  String DZ;
  String CS;
  String JJ;
  String BZ;
  bool JYBJ;
  String JC;
  String SchoolInfo;
  String RoomInfos;
  String ID;
  String ZZCLBlob;
  String LogCreate;
  String LogUpdate;
  String LogAudit;

  JwEmptyRoomDataPagingResultRowsTeachBuilding({
    this.BDJXLXXID,
    this.JXLBH,
    this.JXLMC,
    this.YWMC,
    this.PYSZM,
    this.BDXQXXID,
    this.ZYBZ,
    this.JZWZK,
    this.JZWLX,
    this.DZ,
    this.CS,
    this.JJ,
    this.BZ,
    this.JYBJ,
    this.JC,
    this.SchoolInfo,
    this.RoomInfos,
    this.ID,
    this.ZZCLBlob,
    this.LogCreate,
    this.LogUpdate,
    this.LogAudit,
  });
  JwEmptyRoomDataPagingResultRowsTeachBuilding.fromJson(
      Map<String, dynamic> json) {
    BDJXLXXID = json['BDJXLXXID']?.toString();
    JXLBH = json['JXLBH']?.toString();
    JXLMC = json['JXLMC']?.toString();
    YWMC = json['YWMC']?.toString();
    PYSZM = json['PYSZM']?.toString();
    BDXQXXID = json['BDXQXXID']?.toString();
    ZYBZ = json['ZYBZ'];
    JZWZK = json['JZWZK']?.toString();
    JZWLX = json['JZWLX']?.toString();
    DZ = json['DZ']?.toString();
    CS = json['CS']?.toString();
    JJ = json['JJ']?.toString();
    BZ = json['BZ']?.toString();
    JYBJ = json['JYBJ'];
    JC = json['JC']?.toString();
    SchoolInfo = json['SchoolInfo']?.toString();
    RoomInfos = json['RoomInfos']?.toString();
    ID = json['ID']?.toString();
    ZZCLBlob = json['ZZCLBlob']?.toString();
    LogCreate = json['_LogCreate']?.toString();
    LogUpdate = json['_LogUpdate']?.toString();
    LogAudit = json['_LogAudit']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['BDJXLXXID'] = BDJXLXXID;
    data['JXLBH'] = JXLBH;
    data['JXLMC'] = JXLMC;
    data['YWMC'] = YWMC;
    data['PYSZM'] = PYSZM;
    data['BDXQXXID'] = BDXQXXID;
    data['ZYBZ'] = ZYBZ;
    data['JZWZK'] = JZWZK;
    data['JZWLX'] = JZWLX;
    data['DZ'] = DZ;
    data['CS'] = CS;
    data['JJ'] = JJ;
    data['BZ'] = BZ;
    data['JYBJ'] = JYBJ;
    data['JC'] = JC;
    data['SchoolInfo'] = SchoolInfo;
    data['RoomInfos'] = RoomInfos;
    data['ID'] = ID;
    data['ZZCLBlob'] = ZZCLBlob;
    data['_LogCreate'] = LogCreate;
    data['_LogUpdate'] = LogUpdate;
    data['_LogAudit'] = LogAudit;
    return data;
  }
}

class JwEmptyRoomDataPagingResultRowsSchoolInfo {
/*
{
  "BDXQXXID": null,
  "XQBH": "01",
  "XQMC": "东校区",
  "YWMC": null,
  "PYSZM": null,
  "JJ": null,
  "BZ": null,
  "JYBJ": false,
  "AreaInfos": null,
  "ClassInfos": null,
  "RoomInfos": null,
  "TeachBuildings": null,
  "UserDataPowerSchools": null,
  "ID": "3c99f86b-128d-4267-950d-6e676a5e8744",
  "ZZCLBlob": null,
  "_LogCreate": null,
  "_LogUpdate": null,
  "_LogAudit": null
} 
*/

  String BDXQXXID;
  String XQBH;
  String XQMC;
  String YWMC;
  String PYSZM;
  String JJ;
  String BZ;
  bool JYBJ;
  String AreaInfos;
  String ClassInfos;
  String RoomInfos;
  String TeachBuildings;
  String UserDataPowerSchools;
  String ID;
  String ZZCLBlob;
  String LogCreate;
  String LogUpdate;
  String LogAudit;

  JwEmptyRoomDataPagingResultRowsSchoolInfo({
    this.BDXQXXID,
    this.XQBH,
    this.XQMC,
    this.YWMC,
    this.PYSZM,
    this.JJ,
    this.BZ,
    this.JYBJ,
    this.AreaInfos,
    this.ClassInfos,
    this.RoomInfos,
    this.TeachBuildings,
    this.UserDataPowerSchools,
    this.ID,
    this.ZZCLBlob,
    this.LogCreate,
    this.LogUpdate,
    this.LogAudit,
  });
  JwEmptyRoomDataPagingResultRowsSchoolInfo.fromJson(
      Map<String, dynamic> json) {
    BDXQXXID = json['BDXQXXID']?.toString();
    XQBH = json['XQBH']?.toString();
    XQMC = json['XQMC']?.toString();
    YWMC = json['YWMC']?.toString();
    PYSZM = json['PYSZM']?.toString();
    JJ = json['JJ']?.toString();
    BZ = json['BZ']?.toString();
    JYBJ = json['JYBJ'];
    AreaInfos = json['AreaInfos']?.toString();
    ClassInfos = json['ClassInfos']?.toString();
    RoomInfos = json['RoomInfos']?.toString();
    TeachBuildings = json['TeachBuildings']?.toString();
    UserDataPowerSchools = json['UserDataPowerSchools']?.toString();
    ID = json['ID']?.toString();
    ZZCLBlob = json['ZZCLBlob']?.toString();
    LogCreate = json['_LogCreate']?.toString();
    LogUpdate = json['_LogUpdate']?.toString();
    LogAudit = json['_LogAudit']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['BDXQXXID'] = BDXQXXID;
    data['XQBH'] = XQBH;
    data['XQMC'] = XQMC;
    data['YWMC'] = YWMC;
    data['PYSZM'] = PYSZM;
    data['JJ'] = JJ;
    data['BZ'] = BZ;
    data['JYBJ'] = JYBJ;
    data['AreaInfos'] = AreaInfos;
    data['ClassInfos'] = ClassInfos;
    data['RoomInfos'] = RoomInfos;
    data['TeachBuildings'] = TeachBuildings;
    data['UserDataPowerSchools'] = UserDataPowerSchools;
    data['ID'] = ID;
    data['ZZCLBlob'] = ZZCLBlob;
    data['_LogCreate'] = LogCreate;
    data['_LogUpdate'] = LogUpdate;
    data['_LogAudit'] = LogAudit;
    return data;
  }
}

class JwEmptyRoomDataPagingResultRowsAreaInfo {
/*
{
  "BDFQXXID": null,
  "FQBH": "01",
  "FQMC": "东区第一教学楼东配楼",
  "YWMC": null,
  "PYSZM": null,
  "BDXQXXID": null,
  "ZYBZ": false,
  "TYCBJ": false,
  "JJ": null,
  "BZ": null,
  "JYBJ": false,
  "SchoolInfo": null,
  "RoomInfos": null,
  "ID": "af38ad83-98c0-4a15-9e3b-90a402ec53ff",
  "ZZCLBlob": null,
  "_LogCreate": null,
  "_LogUpdate": null,
  "_LogAudit": null
} 
*/

  String BDFQXXID;
  String FQBH;
  String FQMC;
  String YWMC;
  String PYSZM;
  String BDXQXXID;
  bool ZYBZ;
  bool TYCBJ;
  String JJ;
  String BZ;
  bool JYBJ;
  String SchoolInfo;
  String RoomInfos;
  String ID;
  String ZZCLBlob;
  String LogCreate;
  String LogUpdate;
  String LogAudit;

  JwEmptyRoomDataPagingResultRowsAreaInfo({
    this.BDFQXXID,
    this.FQBH,
    this.FQMC,
    this.YWMC,
    this.PYSZM,
    this.BDXQXXID,
    this.ZYBZ,
    this.TYCBJ,
    this.JJ,
    this.BZ,
    this.JYBJ,
    this.SchoolInfo,
    this.RoomInfos,
    this.ID,
    this.ZZCLBlob,
    this.LogCreate,
    this.LogUpdate,
    this.LogAudit,
  });
  JwEmptyRoomDataPagingResultRowsAreaInfo.fromJson(Map<String, dynamic> json) {
    BDFQXXID = json['BDFQXXID']?.toString();
    FQBH = json['FQBH']?.toString();
    FQMC = json['FQMC']?.toString();
    YWMC = json['YWMC']?.toString();
    PYSZM = json['PYSZM']?.toString();
    BDXQXXID = json['BDXQXXID']?.toString();
    ZYBZ = json['ZYBZ'];
    TYCBJ = json['TYCBJ'];
    JJ = json['JJ']?.toString();
    BZ = json['BZ']?.toString();
    JYBJ = json['JYBJ'];
    SchoolInfo = json['SchoolInfo']?.toString();
    RoomInfos = json['RoomInfos']?.toString();
    ID = json['ID']?.toString();
    ZZCLBlob = json['ZZCLBlob']?.toString();
    LogCreate = json['_LogCreate']?.toString();
    LogUpdate = json['_LogUpdate']?.toString();
    LogAudit = json['_LogAudit']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['BDFQXXID'] = BDFQXXID;
    data['FQBH'] = FQBH;
    data['FQMC'] = FQMC;
    data['YWMC'] = YWMC;
    data['PYSZM'] = PYSZM;
    data['BDXQXXID'] = BDXQXXID;
    data['ZYBZ'] = ZYBZ;
    data['TYCBJ'] = TYCBJ;
    data['JJ'] = JJ;
    data['BZ'] = BZ;
    data['JYBJ'] = JYBJ;
    data['SchoolInfo'] = SchoolInfo;
    data['RoomInfos'] = RoomInfos;
    data['ID'] = ID;
    data['ZZCLBlob'] = ZZCLBlob;
    data['_LogCreate'] = LogCreate;
    data['_LogUpdate'] = LogUpdate;
    data['_LogAudit'] = LogAudit;
    return data;
  }
}

class JwEmptyRoomDataPagingResultRows {
/*
{
  "BDJSXXID": "bcedb481-1a50-4b2b-9d83-5c3b059ffd69",
  "JSBH": "01030003",
  "JSMC": "东1东203",
  "YWMC": null,
  "PYSZM": null,
  "RNRS": 234,
  "RNKSRS": 0,
  "RNBS": 0,
  "BDXQXXID": null,
  "BDFQXXID": null,
  "BDJXLXXID": null,
  "JSLX": "多媒体教室",
  "ZYBZ": false,
  "JSYH": null,
  "KSBSBJ": false,
  "SZLC": null,
  "ZYGDBJ": false,
  "KTBJ": false,
  "JJ": null,
  "BZ": null,
  "JYBJ": false,
  "AreaInfo": {
    "BDFQXXID": null,
    "FQBH": "01",
    "FQMC": "东区第一教学楼东配楼",
    "YWMC": null,
    "PYSZM": null,
    "BDXQXXID": null,
    "ZYBZ": false,
    "TYCBJ": false,
    "JJ": null,
    "BZ": null,
    "JYBJ": false,
    "SchoolInfo": null,
    "RoomInfos": null,
    "ID": "af38ad83-98c0-4a15-9e3b-90a402ec53ff",
    "ZZCLBlob": null,
    "_LogCreate": null,
    "_LogUpdate": null,
    "_LogAudit": null
  },
  "SchoolInfo": {
    "BDXQXXID": null,
    "XQBH": "01",
    "XQMC": "东校区",
    "YWMC": null,
    "PYSZM": null,
    "JJ": null,
    "BZ": null,
    "JYBJ": false,
    "AreaInfos": null,
    "ClassInfos": null,
    "RoomInfos": null,
    "TeachBuildings": null,
    "UserDataPowerSchools": null,
    "ID": "3c99f86b-128d-4267-950d-6e676a5e8744",
    "ZZCLBlob": null,
    "_LogCreate": null,
    "_LogUpdate": null,
    "_LogAudit": null
  },
  "TeachBuilding": {
    "BDJXLXXID": null,
    "JXLBH": "0001",
    "JXLMC": "东区第一教学楼东配楼",
    "YWMC": null,
    "PYSZM": null,
    "BDXQXXID": null,
    "ZYBZ": false,
    "JZWZK": null,
    "JZWLX": null,
    "DZ": null,
    "CS": null,
    "JJ": null,
    "BZ": null,
    "JYBJ": false,
    "JC": null,
    "SchoolInfo": null,
    "RoomInfos": null,
    "ID": "d91cc53c-a9ad-4be3-becf-7f3ed62e8762",
    "ZZCLBlob": null,
    "_LogCreate": null,
    "_LogUpdate": null,
    "_LogAudit": null
  },
  "ClassInfos": null,
  "RoomDepartments": null,
  "Departments": null,
  "RoomInfoSetLessonInfos": null,
  "RoomDepartmentNames": null,
  "EmptyWSeciton": null,
  "ISKJSCX": false,
  "QZ": 0,
  "IsConflict": false,
  "ID": "bcedb481-1a50-4b2b-9d83-5c3b059ffd69",
  "ZZCLBlob": null,
  "_LogCreate": null,
  "_LogUpdate": null,
  "_LogAudit": null
} 
*/

  String BDJSXXID;
  String JSBH;
  String JSMC;
  String YWMC;
  String PYSZM;
  int RNRS;
  int RNKSRS;
  int RNBS;
  String BDXQXXID;
  String BDFQXXID;
  String BDJXLXXID;
  String JSLX;
  bool ZYBZ;
  String JSYH;
  bool KSBSBJ;
  String SZLC;
  bool ZYGDBJ;
  bool KTBJ;
  String JJ;
  String BZ;
  bool JYBJ;
  JwEmptyRoomDataPagingResultRowsAreaInfo AreaInfo;
  JwEmptyRoomDataPagingResultRowsSchoolInfo SchoolInfo;
  JwEmptyRoomDataPagingResultRowsTeachBuilding TeachBuilding;
  String ClassInfos;
  String RoomDepartments;
  String Departments;
  String RoomInfoSetLessonInfos;
  String RoomDepartmentNames;
  String EmptyWSeciton;
  bool ISKJSCX;
  int QZ;
  bool IsConflict;
  String ID;
  String ZZCLBlob;
  String LogCreate;
  String LogUpdate;
  String LogAudit;

  JwEmptyRoomDataPagingResultRows({
    this.BDJSXXID,
    this.JSBH,
    this.JSMC,
    this.YWMC,
    this.PYSZM,
    this.RNRS,
    this.RNKSRS,
    this.RNBS,
    this.BDXQXXID,
    this.BDFQXXID,
    this.BDJXLXXID,
    this.JSLX,
    this.ZYBZ,
    this.JSYH,
    this.KSBSBJ,
    this.SZLC,
    this.ZYGDBJ,
    this.KTBJ,
    this.JJ,
    this.BZ,
    this.JYBJ,
    this.AreaInfo,
    this.SchoolInfo,
    this.TeachBuilding,
    this.ClassInfos,
    this.RoomDepartments,
    this.Departments,
    this.RoomInfoSetLessonInfos,
    this.RoomDepartmentNames,
    this.EmptyWSeciton,
    this.ISKJSCX,
    this.QZ,
    this.IsConflict,
    this.ID,
    this.ZZCLBlob,
    this.LogCreate,
    this.LogUpdate,
    this.LogAudit,
  });
  JwEmptyRoomDataPagingResultRows.fromJson(Map<String, dynamic> json) {
    BDJSXXID = json['BDJSXXID']?.toString();
    JSBH = json['JSBH']?.toString();
    JSMC = json['JSMC']?.toString();
    YWMC = json['YWMC']?.toString();
    PYSZM = json['PYSZM']?.toString();
    RNRS = json['RNRS']?.toInt();
    RNKSRS = json['RNKSRS']?.toInt();
    RNBS = json['RNBS']?.toInt();
    BDXQXXID = json['BDXQXXID']?.toString();
    BDFQXXID = json['BDFQXXID']?.toString();
    BDJXLXXID = json['BDJXLXXID']?.toString();
    JSLX = json['JSLX']?.toString();
    ZYBZ = json['ZYBZ'];
    JSYH = json['JSYH']?.toString();
    KSBSBJ = json['KSBSBJ'];
    SZLC = json['SZLC']?.toString();
    ZYGDBJ = json['ZYGDBJ'];
    KTBJ = json['KTBJ'];
    JJ = json['JJ']?.toString();
    BZ = json['BZ']?.toString();
    JYBJ = json['JYBJ'];
    AreaInfo = (json['AreaInfo'] != null)
        ? JwEmptyRoomDataPagingResultRowsAreaInfo.fromJson(json['AreaInfo'])
        : null;
    SchoolInfo = (json['SchoolInfo'] != null)
        ? JwEmptyRoomDataPagingResultRowsSchoolInfo.fromJson(json['SchoolInfo'])
        : null;
    TeachBuilding = (json['TeachBuilding'] != null)
        ? JwEmptyRoomDataPagingResultRowsTeachBuilding.fromJson(
            json['TeachBuilding'])
        : null;
    ClassInfos = json['ClassInfos']?.toString();
    RoomDepartments = json['RoomDepartments']?.toString();
    Departments = json['Departments']?.toString();
    RoomInfoSetLessonInfos = json['RoomInfoSetLessonInfos']?.toString();
    RoomDepartmentNames = json['RoomDepartmentNames']?.toString();
    EmptyWSeciton = json['EmptyWSeciton']?.toString();
    ISKJSCX = json['ISKJSCX'];
    QZ = json['QZ']?.toInt();
    IsConflict = json['IsConflict'];
    ID = json['ID']?.toString();
    ZZCLBlob = json['ZZCLBlob']?.toString();
    LogCreate = json['_LogCreate']?.toString();
    LogUpdate = json['_LogUpdate']?.toString();
    LogAudit = json['_LogAudit']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['BDJSXXID'] = BDJSXXID;
    data['JSBH'] = JSBH;
    data['JSMC'] = JSMC;
    data['YWMC'] = YWMC;
    data['PYSZM'] = PYSZM;
    data['RNRS'] = RNRS;
    data['RNKSRS'] = RNKSRS;
    data['RNBS'] = RNBS;
    data['BDXQXXID'] = BDXQXXID;
    data['BDFQXXID'] = BDFQXXID;
    data['BDJXLXXID'] = BDJXLXXID;
    data['JSLX'] = JSLX;
    data['ZYBZ'] = ZYBZ;
    data['JSYH'] = JSYH;
    data['KSBSBJ'] = KSBSBJ;
    data['SZLC'] = SZLC;
    data['ZYGDBJ'] = ZYGDBJ;
    data['KTBJ'] = KTBJ;
    data['JJ'] = JJ;
    data['BZ'] = BZ;
    data['JYBJ'] = JYBJ;
    if (AreaInfo != null) {
      data['AreaInfo'] = AreaInfo.toJson();
    }
    if (SchoolInfo != null) {
      data['SchoolInfo'] = SchoolInfo.toJson();
    }
    if (TeachBuilding != null) {
      data['TeachBuilding'] = TeachBuilding.toJson();
    }
    data['ClassInfos'] = ClassInfos;
    data['RoomDepartments'] = RoomDepartments;
    data['Departments'] = Departments;
    data['RoomInfoSetLessonInfos'] = RoomInfoSetLessonInfos;
    data['RoomDepartmentNames'] = RoomDepartmentNames;
    data['EmptyWSeciton'] = EmptyWSeciton;
    data['ISKJSCX'] = ISKJSCX;
    data['QZ'] = QZ;
    data['IsConflict'] = IsConflict;
    data['ID'] = ID;
    data['ZZCLBlob'] = ZZCLBlob;
    data['_LogCreate'] = LogCreate;
    data['_LogUpdate'] = LogUpdate;
    data['_LogAudit'] = LogAudit;
    return data;
  }
}

class JwEmptyRoomDataPagingResult {
/*
{
  "Total": 2,
  "Rows": [
    {
      "BDJSXXID": "bcedb481-1a50-4b2b-9d83-5c3b059ffd69",
      "JSBH": "01030003",
      "JSMC": "东1东203",
      "YWMC": null,
      "PYSZM": null,
      "RNRS": 234,
      "RNKSRS": 0,
      "RNBS": 0,
      "BDXQXXID": null,
      "BDFQXXID": null,
      "BDJXLXXID": null,
      "JSLX": "多媒体教室",
      "ZYBZ": false,
      "JSYH": null,
      "KSBSBJ": false,
      "SZLC": null,
      "ZYGDBJ": false,
      "KTBJ": false,
      "JJ": null,
      "BZ": null,
      "JYBJ": false,
      "AreaInfo": {
        "BDFQXXID": null,
        "FQBH": "01",
        "FQMC": "东区第一教学楼东配楼",
        "YWMC": null,
        "PYSZM": null,
        "BDXQXXID": null,
        "ZYBZ": false,
        "TYCBJ": false,
        "JJ": null,
        "BZ": null,
        "JYBJ": false,
        "SchoolInfo": null,
        "RoomInfos": null,
        "ID": "af38ad83-98c0-4a15-9e3b-90a402ec53ff",
        "ZZCLBlob": null,
        "_LogCreate": null,
        "_LogUpdate": null,
        "_LogAudit": null
      },
      "SchoolInfo": {
        "BDXQXXID": null,
        "XQBH": "01",
        "XQMC": "东校区",
        "YWMC": null,
        "PYSZM": null,
        "JJ": null,
        "BZ": null,
        "JYBJ": false,
        "AreaInfos": null,
        "ClassInfos": null,
        "RoomInfos": null,
        "TeachBuildings": null,
        "UserDataPowerSchools": null,
        "ID": "3c99f86b-128d-4267-950d-6e676a5e8744",
        "ZZCLBlob": null,
        "_LogCreate": null,
        "_LogUpdate": null,
        "_LogAudit": null
      },
      "TeachBuilding": {
        "BDJXLXXID": null,
        "JXLBH": "0001",
        "JXLMC": "东区第一教学楼东配楼",
        "YWMC": null,
        "PYSZM": null,
        "BDXQXXID": null,
        "ZYBZ": false,
        "JZWZK": null,
        "JZWLX": null,
        "DZ": null,
        "CS": null,
        "JJ": null,
        "BZ": null,
        "JYBJ": false,
        "JC": null,
        "SchoolInfo": null,
        "RoomInfos": null,
        "ID": "d91cc53c-a9ad-4be3-becf-7f3ed62e8762",
        "ZZCLBlob": null,
        "_LogCreate": null,
        "_LogUpdate": null,
        "_LogAudit": null
      },
      "ClassInfos": null,
      "RoomDepartments": null,
      "Departments": null,
      "RoomInfoSetLessonInfos": null,
      "RoomDepartmentNames": null,
      "EmptyWSeciton": null,
      "ISKJSCX": false,
      "QZ": 0,
      "IsConflict": false,
      "ID": "bcedb481-1a50-4b2b-9d83-5c3b059ffd69",
      "ZZCLBlob": null,
      "_LogCreate": null,
      "_LogUpdate": null,
      "_LogAudit": null
    }
  ],
  "VerifyRelationsList": null
} 
*/

  int Total;
  List<JwEmptyRoomDataPagingResultRows> Rows;
  String VerifyRelationsList;

  JwEmptyRoomDataPagingResult({
    this.Total,
    this.Rows,
    this.VerifyRelationsList,
  });
  JwEmptyRoomDataPagingResult.fromJson(Map<String, dynamic> json) {
    Total = json['Total']?.toInt();
    if (json['Rows'] != null) {
      final v = json['Rows'];
      final arr0 = <JwEmptyRoomDataPagingResultRows>[];
      v.forEach((v) {
        arr0.add(JwEmptyRoomDataPagingResultRows.fromJson(v));
      });
      Rows = arr0;
    }
    VerifyRelationsList = json['VerifyRelationsList']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Total'] = Total;
    if (Rows != null) {
      final v = Rows;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['Rows'] = arr0;
    }
    data['VerifyRelationsList'] = VerifyRelationsList;
    return data;
  }
}

class JwEmptyRoomData {
/*
{
  "Codes": null,
  "ID": null,
  "Dto": null,
  "Dtos": null,
  "PagingResult": {
    "Total": 2,
    "Rows": [
      {
        "BDJSXXID": "bcedb481-1a50-4b2b-9d83-5c3b059ffd69",
        "JSBH": "01030003",
        "JSMC": "东1东203",
        "YWMC": null,
        "PYSZM": null,
        "RNRS": 234,
        "RNKSRS": 0,
        "RNBS": 0,
        "BDXQXXID": null,
        "BDFQXXID": null,
        "BDJXLXXID": null,
        "JSLX": "多媒体教室",
        "ZYBZ": false,
        "JSYH": null,
        "KSBSBJ": false,
        "SZLC": null,
        "ZYGDBJ": false,
        "KTBJ": false,
        "JJ": null,
        "BZ": null,
        "JYBJ": false,
        "AreaInfo": {
          "BDFQXXID": null,
          "FQBH": "01",
          "FQMC": "东区第一教学楼东配楼",
          "YWMC": null,
          "PYSZM": null,
          "BDXQXXID": null,
          "ZYBZ": false,
          "TYCBJ": false,
          "JJ": null,
          "BZ": null,
          "JYBJ": false,
          "SchoolInfo": null,
          "RoomInfos": null,
          "ID": "af38ad83-98c0-4a15-9e3b-90a402ec53ff",
          "ZZCLBlob": null,
          "_LogCreate": null,
          "_LogUpdate": null,
          "_LogAudit": null
        },
        "SchoolInfo": {
          "BDXQXXID": null,
          "XQBH": "01",
          "XQMC": "东校区",
          "YWMC": null,
          "PYSZM": null,
          "JJ": null,
          "BZ": null,
          "JYBJ": false,
          "AreaInfos": null,
          "ClassInfos": null,
          "RoomInfos": null,
          "TeachBuildings": null,
          "UserDataPowerSchools": null,
          "ID": "3c99f86b-128d-4267-950d-6e676a5e8744",
          "ZZCLBlob": null,
          "_LogCreate": null,
          "_LogUpdate": null,
          "_LogAudit": null
        },
        "TeachBuilding": {
          "BDJXLXXID": null,
          "JXLBH": "0001",
          "JXLMC": "东区第一教学楼东配楼",
          "YWMC": null,
          "PYSZM": null,
          "BDXQXXID": null,
          "ZYBZ": false,
          "JZWZK": null,
          "JZWLX": null,
          "DZ": null,
          "CS": null,
          "JJ": null,
          "BZ": null,
          "JYBJ": false,
          "JC": null,
          "SchoolInfo": null,
          "RoomInfos": null,
          "ID": "d91cc53c-a9ad-4be3-becf-7f3ed62e8762",
          "ZZCLBlob": null,
          "_LogCreate": null,
          "_LogUpdate": null,
          "_LogAudit": null
        },
        "ClassInfos": null,
        "RoomDepartments": null,
        "Departments": null,
        "RoomInfoSetLessonInfos": null,
        "RoomDepartmentNames": null,
        "EmptyWSeciton": null,
        "ISKJSCX": false,
        "QZ": 0,
        "IsConflict": false,
        "ID": "bcedb481-1a50-4b2b-9d83-5c3b059ffd69",
        "ZZCLBlob": null,
        "_LogCreate": null,
        "_LogUpdate": null,
        "_LogAudit": null
      }
    ],
    "VerifyRelationsList": null
  },
  "OperationResult": null,
  "PermissionResult": null
} 
*/

  String Codes;
  String ID;
  String Dto;
  String Dtos;
  JwEmptyRoomDataPagingResult PagingResult;
  String OperationResult;
  String PermissionResult;

  JwEmptyRoomData({
    this.Codes,
    this.ID,
    this.Dto,
    this.Dtos,
    this.PagingResult,
    this.OperationResult,
    this.PermissionResult,
  });
  JwEmptyRoomData.fromJson(Map<String, dynamic> json) {
    Codes = json['Codes']?.toString();
    ID = json['ID']?.toString();
    Dto = json['Dto']?.toString();
    Dtos = json['Dtos']?.toString();
    PagingResult = (json['PagingResult'] != null)
        ? JwEmptyRoomDataPagingResult.fromJson(json['PagingResult'])
        : null;
    OperationResult = json['OperationResult']?.toString();
    PermissionResult = json['PermissionResult']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Codes'] = Codes;
    data['ID'] = ID;
    data['Dto'] = Dto;
    data['Dtos'] = Dtos;
    if (PagingResult != null) {
      data['PagingResult'] = PagingResult.toJson();
    }
    data['OperationResult'] = OperationResult;
    data['PermissionResult'] = PermissionResult;
    return data;
  }
}

class JwEmptyRoom {
/*
{
  "state": 0,
  "message": null,
  "data": {
    "Codes": null,
    "ID": null,
    "Dto": null,
    "Dtos": null,
    "PagingResult": {
      "Total": 2,
      "Rows": [
        {
          "BDJSXXID": "bcedb481-1a50-4b2b-9d83-5c3b059ffd69",
          "JSBH": "01030003",
          "JSMC": "东1东203",
          "YWMC": null,
          "PYSZM": null,
          "RNRS": 234,
          "RNKSRS": 0,
          "RNBS": 0,
          "BDXQXXID": null,
          "BDFQXXID": null,
          "BDJXLXXID": null,
          "JSLX": "多媒体教室",
          "ZYBZ": false,
          "JSYH": null,
          "KSBSBJ": false,
          "SZLC": null,
          "ZYGDBJ": false,
          "KTBJ": false,
          "JJ": null,
          "BZ": null,
          "JYBJ": false,
          "AreaInfo": {
            "BDFQXXID": null,
            "FQBH": "01",
            "FQMC": "东区第一教学楼东配楼",
            "YWMC": null,
            "PYSZM": null,
            "BDXQXXID": null,
            "ZYBZ": false,
            "TYCBJ": false,
            "JJ": null,
            "BZ": null,
            "JYBJ": false,
            "SchoolInfo": null,
            "RoomInfos": null,
            "ID": "af38ad83-98c0-4a15-9e3b-90a402ec53ff",
            "ZZCLBlob": null,
            "_LogCreate": null,
            "_LogUpdate": null,
            "_LogAudit": null
          },
          "SchoolInfo": {
            "BDXQXXID": null,
            "XQBH": "01",
            "XQMC": "东校区",
            "YWMC": null,
            "PYSZM": null,
            "JJ": null,
            "BZ": null,
            "JYBJ": false,
            "AreaInfos": null,
            "ClassInfos": null,
            "RoomInfos": null,
            "TeachBuildings": null,
            "UserDataPowerSchools": null,
            "ID": "3c99f86b-128d-4267-950d-6e676a5e8744",
            "ZZCLBlob": null,
            "_LogCreate": null,
            "_LogUpdate": null,
            "_LogAudit": null
          },
          "TeachBuilding": {
            "BDJXLXXID": null,
            "JXLBH": "0001",
            "JXLMC": "东区第一教学楼东配楼",
            "YWMC": null,
            "PYSZM": null,
            "BDXQXXID": null,
            "ZYBZ": false,
            "JZWZK": null,
            "JZWLX": null,
            "DZ": null,
            "CS": null,
            "JJ": null,
            "BZ": null,
            "JYBJ": false,
            "JC": null,
            "SchoolInfo": null,
            "RoomInfos": null,
            "ID": "d91cc53c-a9ad-4be3-becf-7f3ed62e8762",
            "ZZCLBlob": null,
            "_LogCreate": null,
            "_LogUpdate": null,
            "_LogAudit": null
          },
          "ClassInfos": null,
          "RoomDepartments": null,
          "Departments": null,
          "RoomInfoSetLessonInfos": null,
          "RoomDepartmentNames": null,
          "EmptyWSeciton": null,
          "ISKJSCX": false,
          "QZ": 0,
          "IsConflict": false,
          "ID": "bcedb481-1a50-4b2b-9d83-5c3b059ffd69",
          "ZZCLBlob": null,
          "_LogCreate": null,
          "_LogUpdate": null,
          "_LogAudit": null
        }
      ],
      "VerifyRelationsList": null
    },
    "OperationResult": null,
    "PermissionResult": null
  }
} 
*/

  int state;
  String message;
  JwEmptyRoomData data;

  JwEmptyRoom({
    this.state,
    this.message,
    this.data,
  });
  JwEmptyRoom.fromJson(Map<String, dynamic> json) {
    state = json['state']?.toInt();
    message = json['message']?.toString();
    data =
        (json['data'] != null) ? JwEmptyRoomData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['state'] = state;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}
