///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class JwKbpro {
/*
{
  "beginSection": "1",
  "buildingName": "西区第一教学楼",
  "campus": "西校区",
  "classroomName": "西1教502多",
  "courseName": "财务报表分析",
  "courseType": "理论",
  "dayOfWeek": "2",
  "endSection": "2",
  "isUndergraduate": "1",
  "teacherName": "车正红",
  "weekDescription": "0111111100000000000000000"
} 
*/

  String beginSection;
  String buildingName;
  String campus;
  String classroomName;
  String courseName;
  String courseType;
  String dayOfWeek;
  String endSection;
  String isUndergraduate;
  String teacherName;
  String weekDescription;

  JwKbpro({
    this.beginSection,
    this.buildingName,
    this.campus,
    this.classroomName,
    this.courseName,
    this.courseType,
    this.dayOfWeek,
    this.endSection,
    this.isUndergraduate,
    this.teacherName,
    this.weekDescription,
  });
  JwKbpro.fromJson(Map<String, dynamic> json) {
    beginSection = json['beginSection']?.toString();
    buildingName = json['buildingName']?.toString();
    campus = json['campus']?.toString();
    classroomName = json['classroomName']?.toString();
    courseName = json['courseName']?.toString();
    courseType = json['courseType']?.toString();
    dayOfWeek = json['dayOfWeek']?.toString();
    endSection = json['endSection']?.toString();
    isUndergraduate = json['isUndergraduate']?.toString();
    teacherName = json['teacherName']?.toString();
    weekDescription = json['weekDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['beginSection'] = beginSection;
    data['buildingName'] = buildingName;
    data['campus'] = campus;
    data['classroomName'] = classroomName;
    data['courseName'] = courseName;
    data['courseType'] = courseType;
    data['dayOfWeek'] = dayOfWeek;
    data['endSection'] = endSection;
    data['isUndergraduate'] = isUndergraduate;
    data['teacherName'] = teacherName;
    data['weekDescription'] = weekDescription;
    return data;
  }
}
